import javax.swing.*;
import java.awt.*;
import java.awt.event.*;

/**
  * The class <code>BoardController</code> is used to control the differents actions in the board
  * @version 0.2
  * @author Dorian Terbah, Thomas Béchet
**/

public class BoardController implements MouseListener, ActionListener{

	/**
	  * The actual session of the game
	  * @see Session
	**/
	private Session session;

	/**
	  * Construtor of the BoardController 
	  * @param session It's the actual session of the game
	**/
	public BoardController(Session session){

		this.session = session;
	}

	@Override

	/**
	  * @param event
	  *				the event generated by the pressure of a cell
	**/
	public void actionPerformed(ActionEvent event){
		Cell cell = (Cell)event.getSource();

		this.session.clickCell(cell);
	}
	@Override
	/**
	  * @param event
	  *				the event generated by the click on a cell, particulary by the right click
	**/
	public void mouseClicked(MouseEvent event){
		Cell cell = (Cell)event.getSource();

		if(event.getButton() == MouseEvent.BUTTON3)
			this.session.changeCellMode(cell);
	}
	@Override 
	public void mouseEntered(MouseEvent event){}
	@Override
	public void mouseExited(MouseEvent event){}
	@Override
	public void mousePressed(MouseEvent event){}
	@Override
	public void mouseReleased(MouseEvent event){}
}